FROM node:10

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

ENV APP_SETTINGS_FILE_PATH '/usr/src/app/config/appSettings.dev.json'

ENV PORT 8080

ENV JAWSDB_URL 'mysql://root:@mysql/barsnap'

ENV REDIS_URL 'redis://redis'

EXPOSE 8080

CMD [ "node", "app.js" ]
