version: '3'
services:
  mysql:
    image: mysql:5.7.30
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=sipstir
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    expose:
      - "6379"
    volumes:
      - redis:/var/lib/redis
  sipstir-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    links:
      - mysql
      - redis
volumes:
  mysql:
  redis:
