version: "3"
services:
  postgres:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=sipstir
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    # ports:
    #   - 3306:3306
    volumes:
      - postgres:/var/lib/postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sipstir.app
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5050:80
    links:
      - postgres
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    expose:
      - "6379"
    volumes:
      - redis:/var/lib/redis
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    links:
      - postgres
      - redis
volumes:
  postgres:
  redis:
