version: "3"
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=sipstir
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    expose:
      - "6379"
    volumes:
      - redis:/var/lib/redis
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8080
    links:
      - mysql
      - redis
volumes:
  mysql:
  redis:
