version: '3'
services:
  mysql:
    image: mysql:5.7.30
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=barsnap
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  barsnap-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    links:
      - mysql
volumes:
  mysql: