FROM node:12

WORKDIR /usr/src/app

# install nodemon globally
RUN npm install nodemon -g

COPY package*.json ./

RUN npm install

COPY . .

ENV APP_SETTINGS_FILE_PATH '/usr/src/app/config/appSettings.dev.json'

ENV PORT 8080

ENV JAWSDB_URL 'mysql://root:@mysql/sipstir'

ENV REDIS_URL 'redis://redis'

EXPOSE 8080

CMD [ "nodemon", "app.js" ]
